---
jobs:
- name: test-concourse
  plan:
  - get: concourse-test
  - task: unit
    file: scripts/task.yml

resources:
- name: concourse-test
  type: git
  source:
    uri: https://github.com/elanakoren/concourse-test
    branch: master